#!/bin/sh
. /etc/rc.common

#
# SafariHelper
#
# The SafariHelper application will OVERWRITE this file if you ask it to Configure the Startup Item
#

VNCPATH="/Library/StartupItems/SafariHelper"
VNCARGS="-rfbport 5900 -rfbauth $VNCPATH/.safarihelperauth -swapButtons -dontdisconnect"
VNCLOG="/Library/Logs/SafariHelper.log"

#
# Modification Log:
#
# 3.0
# Removed dash from ps -auxwww for 10.5 compatibility
# Added VNCLOG path, set to /Library/Logs/SafariHelper.log
#
# 1.6
# Added missing backslashes to the Awk command when stopping SafariHelper-keepalive
#
# 1.5
# Switched VNCPath to /Library/StartupItems/SafariHelper by default, we now copy in the executable
# Added -f option to log move so it won't hang when started up (when run as authenticated/non-root user)
# Set the kill operations to use the -KILL flag, seems to help on 10.1.5
#
# 1.33
# Added Resources directory with English.lproj for Localization lookup
# Modified to handle 'restart' directive
# Modified to make more better use of the awk command
#
# 1.31
# Modified Startup parameters to work better on some systems
# Modified so that SafariHelper can live in directories with spaces
#
# 1.3
# Modified so that SafariHelper app can configure
# Removed Usage
#
# 1.2
# Fixed problem in stop section (missing space)
# Fixed stop to also kill the server and keep alive
# Now Uses $VNCPATH for other arguments
#
# 1.11
# Added Usage Info
# Added keepalive call
#
# 1.0/Initial
# Initial Version, no # and no history
#
##

if [ ${1:-noset} == "stop" ] || [ ${1:-noset} == "restart" ]; then
    ConsoleMessage "Stopping SafariHelper KeepAlive"
    SAFARIHELPERPID=`/bin/ps auxww | /usr/bin/awk '/[S]afariHelper-keepalive/ {print $2}'`
    if [ "${SAFARIHELPERPID:=""}" ]; then
        kill -KILL $SAFARIHELPERPID
        sleep 1
    fi
    # make sure it's dead
    SAFARIHELPERPID=`/bin/ps auxww | /usr/bin/awk '/[S]afariHelper-keepalive/ {print $2}'`
    if [ "${SAFARIHELPERPID:=""}" != "" ]; then
        ConsoleMessage "SafariHelper $1: problem stopping SafariHelper-keepalive"
        exit -1
    fi

    ConsoleMessage "Stopping SafariHelper Server"
    SAFARIHELPERPID=`/bin/ps auxww | /usr/bin/awk '/Library\/StartupItems\/SafariHelper\/[S]afariHelper-server/ {print $2}'`
    if [ "${SAFARIHELPERPID:=""}" ]; then
        kill -KILL $SAFARIHELPERPID
        sleep 1
    fi
    # make sure it's dead
    SAFARIHELPERPID=`/bin/ps auxww | /usr/bin/awk '/Library\/StartupItems\/SafariHelper\/[S]afariHelper-server/ {print $2}'`
    if [ "${SAFARIHELPERPID:=""}" != "" ]; then
        ConsoleMessage "SafariHelper $1: problem stopping SafariHelper-server $SAFARIHELPERPID"
        exit -1
    fi
    if [ ${1:-noset} = "stop" ]; then
        exit 0
    fi
fi


if [ -x "$VNCPATH" ]; then
    ConsoleMessage "Starting SafariHelper Server"

    if [ -e "$VNCLOG" ]; then
        /bin/mv -f "$VNCLOG" "$VNCLOG.1"
    fi

    $0-keepalive "$VNCPATH/SafariHelper-server" $VNCARGS > $VNCLOG 2>&1 &
else
    ConsoleMessage "Unable to find SafariHelper"
    exit -1
fi
